extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: 中文（简体）
      link: / 
      lang: zh
plugins:
  - search
site_name: Novi Documentation
theme:
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.instant
    - navigation.top
  language: zh
  logo: assets/novi.png
  name: material
  palette:
    primary: blue
nav:
  - Home: index.md
